### PR TITLE
Change wording general simulation structure

### PR DESCRIPTION
**Pull request by worcjamessmith**
I changed the wording as it was a bit confusing to me. Feel free to ignore if you think mine is less clear or I'm missing something

### CODE REVIEW

**Comment by MalikaIhle** [comment]
thanks! I see your point and I do think it's clearer, I'll make tiny edits to it, but otherwise merging it ;)

**Comment by MalikaIhle** [comment]
I changed to:

# General structure of a simulation

1. **define** what type of data and variables need to be simulated, i.e. their **distribution**, their class (e.g. factor vs numerical value), **sample sizes** (within a dataset, and number of replicates), what will need to vary (e.g. the strength of relationship)  

2. **generate data**, random data or data including an effect (e.g. an impose correlation between two variables)  

3. **run the statistical test** you think is appropriate, and record the relevant statistic (e.g. p-value) 

4. **replicate** step 2 and 3 to get the distribution of the statistic of interest  

5. try out different parameter sets (**explore the parameter space** for which results are similar)  

6. **analyze and interpret the combined results of many simulations** within each set of parameters. For instance, check that you only get a significant result in 5% of the simulations (if `alpha = 0.05`) when you simulated no effect; and that you get at a significant result in 80% of the simulations (if `power = 80%`) when you simulated an effect  

because needed to keep numbering and content matching the paper they will have to read and the numbering in the screen shots of the real life example.

**Comment by MalikaIhle** [comment]
actually perhaps I'll say 'if you targeted a power of 80%'
would that be more correct?

**Comment by worcjamessmith** [comment]
I think either is accurate!

**Pull request merged**
